server:
  port: 9291
spring:
  application:
    name: market-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/supermarket_manager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
      username: root
      password: 1234

  redis:
    host: localhost
    port: 6379
    password:
    database: 3
  mvc:
    async:
      request-timeout: 20000
mybatis-plus:
  mapper-locations: classpath:com/rabbiter/market/mapper/*Mapper.xml
logging:
  level:
    cn.dingli.market.mapper: debug



filePath: "/src/main/resources/static/files/"

