server:
  port: 9291
spring:
  application:
    name: market-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://mysql:3306/supermarket_manager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
#      username: root
#      password: 123
      url: jdbc:mysql://127.0.0.1:3306/supermarket_manager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
      username: root
      password: 1234

  servlet:
    multipart:
      max-file-size: 100000MB
      max-request-size: 1000000MB

  redis:
    host: localhost
    port: 6379
    password:
    database: 3
#  redis:
#    host: redis
#    port: 6379
#    password: 123456
#    database: 3
  mvc:
    async:
      request-timeout: 20000
mybatis-plus:
  mapper-locations: classpath:com/rabbiter/market/mapper/*Mapper.xml
logging:
  level:
    cn.dingli.market.mapper: debug



filePath: "/src/main/resources/static/files/"

